version: '3'
services:
  db-citas:
    image: 'postgres:latest'
    container_name: 'db-citas'
    environment:
      - 'POSTGRES_DB=db-citasservice'
      - 'POSTGRES_PASSWORD=citaspw'
      - 'POSTGRES_USER=citas'
    ports:
      - '5402:5432'
    networks:
      - red
  CitasService:
    container_name: 'citasService'
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db-citas
    environment:
      - DATABASE_URL=jdbc:postgresql://db-citas:5432/citasservice
      - DATABASE_USERNAME=citas
      - DATABASE_PASSWORD=citaspw
    ports:
      - '8081:8080'
    expose:
      - "8081"
    networks:
      - red
networks:
  red:
    name: 'red'